name       : osinfo-db
version    : '20230719'
release    : 12
source     :
    - https://releases.pagure.org/libosinfo/osinfo-db-20230719.tar.xz : 13d1c97fc7d67137935dcc97778c08bb079a4f0fe312d479786cea1411e4845a
license    : GPL-2.0-or-later
component  : virt
summary    : OS database for libosinfo
extract    : no
description: |
    Operating system database for libosinfo
builddeps  :
    - osinfo-db-tools
install    : |
    osinfo-db-import --root "$installdir" --system $sources/$package-$version.tar.xz
