name       : osinfo-db
version    : '20190905'
release    : 4
source     :
    - https://releases.pagure.org/libosinfo/osinfo-db-20190905.tar.xz : 7233b5a68cc0c3c231db510f342fcc78f6e7c40ca0a739bff484f66591b0bda3
license    : GPL-2.0-or-later
component  : virt
summary    : OS database for libosinfo
extract    : no
description: |
    Operating system database for libosinfo
builddeps  :
    - osinfo-db-tools
install    : |
    osinfo-db-import --root "$installdir" --system $sources/$package-$version.tar.xz
